### ISSUE TITLE
img2img mode fails (The command "Select" is not currently available.)

### ISSUE THREAD

**Issue by Puncia** [isekaidev/stable.art#14]
I can't seem to make img2img mode work, see video:

[2023-01-18 09-16-09.webm](https://user-images.githubusercontent.com/4633311/213119263-0a2083bb-4651-46c5-b5fd-cf8da934aef4.webm)

using PS 23.3.2

**Comment by Binxly** [comment]
Also experiencing this issue- both with img2img and inpaint. No error appears in the terminal window, and the plugin appears to get stuck attempting to generate an image until it is interrupted.

**Comment by Binxly** [comment]
Fixed my issue. Did a git pull of the latest webUI commit after removing the Dreambooth extension folder.
Hope this helps.

**Comment by Puncia** [comment]
I don't have the Dreambooth extension installed and I just updated to the latest commit too, but I still have the issue

**Comment by isekaidev** [comment]
Does the same happen for the inpaint mode or only img2img?

**Comment by Puncia** [comment]
Also happens with inpaint

**Comment by DarkAlchy** [comment]
I just downloaded this as I needed the ability to finely mask/select for some inpainting work to be hit with this select nonsense.  I filed ticket #18 on it, but it appears tickets are not being looked at, so is this abandoned already?

**Comment by isekaidev** [comment]
> is this abandoned already?

What do you mean? I am still working on other bugs/features, I cannot fix all issues in seconds.

**Comment by DarkAlchy** [comment]
> > is this abandoned already?
> 
> What do you mean? I am still working on other bugs/features, I cannot fix all issues in seconds.

Just wondering since I saw so many tickets without a response out of you.  Glad to know this is being worked on.

**Comment by isekaidev** [comment]
Guys, could you test it again? It should be fixed.

**Comment by DarkAlchy** [comment]
> Guys, could you test it again? It should be fixed.

![image](https://user-images.githubusercontent.com/10561690/213873335-c9eca2d9-4e5a-4d64-ba02-6bdd93bc1d0e.png)

**Comment by isekaidev** [comment]
Could you please record a video like OP? Need to check what happens with layers during generating.

**Comment by DarkAlchy** [comment]
> Could you please record a video like OP? Need to check what happens with layers during generating.

Maybe someone else can, but it is the same for i2i or inpainting only now instead of select it is delete.

**Comment by isekaidev** [comment]
Do you have layers with transparent areas? Try to use inpaint in a document with just one layer without transparent areas, will the error remain?

**Comment by DarkAlchy** [comment]
> Do you have layers with transparent areas? Try to use inpaint in a document with just one layer without transparent areas, will the error remain?

I have only the background layer.  I hit layers flatten and there is nothing to flatten because there is only the one layer.

**Comment by isekaidev** [comment]
Could you verify that your version hash is e029076? I reproduced the deletion error, and yes, it is related to the lock. But the issue with selection should have been fixed in the latest update. If your hash is not e029076, try to close and reopen Photoshop.

<img width="163" alt="image" src="https://user-images.githubusercontent.com/118139897/213874511-e7f82d03-37b9-46d3-9481-a65932388671.png">

**Comment by DarkAlchy** [comment]
![image](https://user-images.githubusercontent.com/10561690/213874998-64001de0-3220-4fcc-9a8e-fd565ab9d832.png)

**Comment by isekaidev** [comment]
@DarkAlchy could you please check again? A new hash should be 387cb83.

**Comment by DarkAlchy** [comment]
> @DarkAlchy could you please check again? A new hash should be [387cb83](https://github.com/isekaidev/stable.art/commit/387cb8351e8d0a251e127bcf8093c286a3f9855f).

![image](https://user-images.githubusercontent.com/10561690/213882852-4e09929e-70ba-421e-95f6-ccec03ed8a30.png)
![image](https://user-images.githubusercontent.com/10561690/213882863-7498afa5-0d6b-449e-99f6-9b793d33d509.png)
![image](https://user-images.githubusercontent.com/10561690/213882870-c41fa521-d2b2-451a-9305-a6348cbf1f6a.png)
![image](https://user-images.githubusercontent.com/10561690/213882878-b9e0ec1d-b6d3-435c-811a-4ec6767ee009.png)

**Comment by isekaidev** [comment]
Cannot reproduce :(
Does your original background layer have any transparent areas? Or is it entirely black? Will the error remain if you create a new document with default settings?

**Comment by DarkAlchy** [comment]
![image](https://user-images.githubusercontent.com/10561690/213883548-89f949f1-b47f-4b44-ae5c-087c2437540e.png)

**Comment by DarkAlchy** [comment]
I2I or Inpainting have the same error.

![image](https://user-images.githubusercontent.com/10561690/213883607-5b47acd2-cd5b-466d-8dc6-d4ab73301069.png)

**Comment by Puncia** [comment]
Same issue here as of https://github.com/isekaidev/stable.art/commit/155019e4af9ef3097257c6e6f34259b12eb28fc9.

**Comment by isekaidev** [comment]
@Puncia What is your photoshop version?

I reproduced the bug, it seems a bug is in Photoshop API itself, and it is related only to old versions (23.3.0 has the bug, 24.1 does not). I added a workaround, and now it should be fixed. Could you test?

**Comment by Puncia** [comment]
Thanks, it seems to be fixed now. I do get `ReferenceError: atob is not defined` when clicking on the result now though, making me unable to use it. Happens with txt2img and inpaint as well.

![image](https://user-images.githubusercontent.com/4633311/213914045-5b0cb5e5-3efb-45e5-a451-ee0d8da2712a.png)

**Comment by DarkAlchy** [comment]
![image](https://user-images.githubusercontent.com/10561690/213914177-07631269-349b-447d-a7a5-0f1a674d7e28.png)

**Comment by isekaidev** [comment]
Fucking adobe with their custom js-engine 😔
I hope it is finally fixed this time.

**Comment by DarkAlchy** [comment]
> Fucking adobe with their custom js-engine 😔 I hope it is finally fixed this time.

I hope so.

**Comment by DarkAlchy** [comment]
Worked for me.

**Comment by Puncia** [comment]
All seems to work well now! thanks again for your efforts, appreciated.
